// <auto-generated />
namespace SurveyME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class string_array_redoV3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(string_array_redoV3));
        
        string IMigrationMetadata.Id
        {
            get { return "202208201428090_string_array_redoV3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
