// <auto-generated />
namespace SurveyME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Surveyquestion_type_V2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Surveyquestion_type_V2));
        
        string IMigrationMetadata.Id
        {
            get { return "202208301829243_Surveyquestion_type_V2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
