// <auto-generated />
namespace SurveyME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class academiclevels_surveyforms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(academiclevels_surveyforms));
        
        string IMigrationMetadata.Id
        {
            get { return "202208161247382_academiclevels_surveyforms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
