// <auto-generated />
namespace SurveyME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class surveyform_typebool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(surveyform_typebool));
        
        string IMigrationMetadata.Id
        {
            get { return "202208151042182_surveyform_typebool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
