// <auto-generated />
namespace SurveyME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recordstracking_V6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recordstracking_V6));
        
        string IMigrationMetadata.Id
        {
            get { return "202208310930045_recordstracking_V6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
